### ISSUE TITLE
RenderWindow getSize and Event Resized gives odd results

### ISSUE THREAD

**Issue by charlieman** [Guigui220D/sfml-wrapper#10]
Hi, I'm trying out the wrapper and was having issues with the `RenderWindow.getSize` giving weird numbers for the height. Also the Size obtained from the resized event give the height value for both width and height. Here's a minimal sample code:

```
const std = @import("std");
const sf = @import("sfml");

pub fn main() !void {
    var window = try sf.RenderWindow.init(.{ .x = 400, .y = 300 }, 32, "Zig window size");
    defer window.deinit();
    {
        const windowSize = window.getSize();
        std.debug.warn("Initial Window Size:: width: {d}, height: {d}\n", .{ windowSize.x, windowSize.y });
    }

    while (window.isOpen()) {
        while (window.pollEvent()) |event| {
            switch (event) {
                .closed => window.close(),
                .resized => |e| {
                    std.debug.warn("Event Size:: width: {d}, height: {d}\n", .{ e.size.x, e.size.y });
                    const windowSize = window.getSize();
                    std.debug.warn("Window Size:: width: {d}, height: {d}\n", .{ windowSize.x, windowSize.y });
                },
                else => {},
            }
        }

        window.clear(sf.Color.Black);
        window.display();
    }
}
```

This returns a large number for the initial height and then the event size has the actual height value for both width and height:
```
Initial Window Size:: width: 400, height: 1421867264
Event Size:: width: 350, height: 350        
Window Size:: width: 495, height: 1421867264
```

I made the same thing using csfml directly to see if the problem comes from there but it works as expected:
```
#include <SFML/Graphics.h>
#include <stdio.h>

int main()
{
    sfVideoMode mode = {400, 300, 32};
    sfRenderWindow *window;
    sfEvent event;

    window = sfRenderWindow_create(mode, "SFML window", sfDefaultStyle, NULL);
    if (!window) {
        return 1;
    }
    {
        sfVector2u windowSize = sfRenderWindow_getSize(window);
        printf("Initial Window Size:: width: %d, height: %d\n", windowSize.x, windowSize.y);
    }

    while (sfRenderWindow_isOpen(window))
    {
        while (sfRenderWindow_pollEvent(window, &event))
        {
            switch (event.type)
            {
            case sfEvtClosed:
            {
                sfRenderWindow_close(window);
                break;
            }
            case sfEvtResized:
            {
                printf("Event  Size:: width: %d, height: %d\n", event.size.width, event.size.height);
                sfVector2u windowSize = sfRenderWindow_getSize(window);
                printf("Window Size:: width: %d, height: %d\n", windowSize.x, windowSize.y);
                break;
            }
            default:
                break;
            }
        }
        sfRenderWindow_clear(window, sfBlack);
        sfRenderWindow_display(window);
    }
}
```

My ultimate objective is to use window.setView to avoid changing the aspect ratio:

    window.setView(sf.View.fromRect(sf.FloatRect.init(0, 0, @intToFloat(f32, e.size.x), @intToFloat(f32, e.size.y))));

**Comment by Guigui220D** [comment]
Hello! this is issue #2 of this project. It is because of zig's [1481 issue](https://github.com/ziglang/zig/issues/1481); because of compatibility with the c abi being incomplete, getters that return structs by value of less than 16 bytes iirc, are broken. I have no idea when it's gonna be fixed sadly :(

Workarounds are to write asm x86 code to read the registers after calling the function (which is ugly, i've done that for *some* functions in that library but it doesn't always work (check [this function](https://github.com/Guigui220D/sfml-wrapper/blob/d1f0a8b6e92a221bba372d0bbb2584284053e864/src/sfml/graphics/image.zig#L66) for instance); or just keep track of what you last set the size to be :)

Thanks for trying my sfml wrapper ^^

**Comment by charlieman** [comment]
Oh, I just noticed the issue with event size is a simple typo in https://github.com/Guigui220D/sfml-wrapper/blob/main/src/sfml/window/event.zig#L38, the height is used in both sides.

**Comment by Guigui220D** [comment]
ah! I'll check that after my dinner

**Comment by charlieman** [comment]
Thank you for your answers! Using event size value fixes my problem :)

**Comment by Guigui220D** [comment]
@charlieman if you ever need some more help or want to give me suggestions or contribute you can text me on discord Ino#7587 :)

**Comment by vagra** [comment]
This problem exists in sfml itself, I searched for the solution on the google and found it here.

Using event size value fixes my problem :)
