### ISSUE TITLE
Capitalisation issue in import in sfml.zig

### ISSUE THREAD

**Issue by tslilc** [Guigui220D/sfml-wrapper#21]
Hi there,

Thanks for writing this wrapper, i'm really enjoying using it. To have it build on `zig-0.9-master` however i had to change the capitalisation of imported files to match the file names, as in the below diff.

```
diff --git a/src/sfml/sfml.zig b/src/sfml/sfml.zig
index 59f9725..da1dc4b 100644
--- a/src/sfml/sfml.zig
+++ b/src/sfml/sfml.zig
@@ -17,8 +17,8 @@ pub const system = struct {
 pub const window = struct {
     pub const Event = @import("window/event.zig").Event;
     pub const Style = @import("window/Style.zig");
-    pub const keyboard = @import("window/Keyboard.zig");
-    pub const mouse = @import("window/Mouse.zig");
+    pub const keyboard = @import("window/keyboard.zig");
+    pub const mouse = @import("window/mouse.zig");
 };

 pub const graphics = struct {
```

**Comment by Guigui220D** [comment]
Would you mind making a pull request for your changes? I don't have access to my code rn, thanks :)

**Comment by tslilc** [comment]
Of course, i opened #22 in response to this, and included the other changes i had needed to make for a working build on master.
